# Site settings
name: JC Blog
email: jianchen319@gmail.com
author: J C
url: http://www.google.com
resume_site: http://www.google.com
github: https://github.com/iamjianchen/
baseurl: ""
description: My Blog
meta_description: (Hopefully...)
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

